### ISSUE TITLE
Dear Mr.mwgeurts!

### ISSUE THREAD

**Issue by forCharlie** [mwgeurts/dicom_tools#18]
First, appreciate it  a lot for your code -'dicom_tools', I ran it by one case and it  worked,but when we tried to
 run another case,the 'loadDICOMStructures' kept throwing:

> 'Error in LoadDICOMStructures (line 265)
>  for subitem = fieldnames(info.ROIContourSequence.(...'

PS:I have been follwing exactly the same steps you mentioned. 
I can't figure it out , could you help me ,please?

**Comment by mwgeurts** [comment]
I'd be happy to look into this. Would you be willing to email me the DICOM file that is failing?

**Comment by forCharlie** [comment]
Yes,thank you!I have just sent it to you.

**Comment by forCharlie** [comment]
Dear Mr.Geurts,
       I know what's wrong now-The RTstucture file ,some of the ROIs don't have contoursequence,thanks anyway.Have a great day!

**Comment by mwgeurts** [comment]
Thanks for the data. I was able to reproduce the problem as well and have added a line in the function to catch structures with missing ContourSequence fields and gracefully ignore them. The function should now work with your dataset. Thanks for finding this issue and letting me know about it!
